CREATE TABLE IF NOT EXISTS Dentista (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
sobrenome VARCHAR(100) NOT NULL,
matricula VARCHAR(100) NOT NULL);

CREATE TABLE IF NOT EXISTS Endereco (
id INT PRIMARY KEY AUTO_INCREMENT,
rua VARCHAR(50) NOT NULL,
numero INT NOT NULL,
cidade VARCHAR(50) NOT NULL,
estado VARCHAR(50) NOT NULL);



